# serverless.yml

service: olga-backend

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: sa-east-1
  environment:
    SERVICE_NAME: ${self:service}

functions:
  createUsers:
    handler: lambdas/lambda1/main
    events:
      - http:
          path: hello
          method: get
          integration: lambda

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: 'api.olga.lat'
    basePath: 'api'
    stage: ${self:provider.stage}
    createRoute53Record: true
