service: olga-backend

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: sa-east-1
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - dynamodb:*
        - s3:*
      Resource: '*'

# you can define service wide environment variables here
#  environment:
#    variable1: value1

functions:
  world:
    handler: lambdas/bin/world
    events:
      - httpApi:
          path: /world
          method: get
      - cloudwatchLog: '/aws/lambda/world'
  go-lambda-create-user:
    handler: lambdas/bin/go-lambda-create-user
    ssmToEnvironment:
      - EMAIL_SENDER_ADDRESS
      - EMAIL_SENDER_PASSWORD
    events:
      - httpApi:
          path: /users
          method: post
      - cloudwatchLog: '/aws/lambda/go-lambda-create-user'
  go-lambda-create-user-rds:
    handler: lambdas/bin/go-lambda-create-user-rds
    ssmToEnvironment:
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - DB_HOST_WRITER
    events:
      - httpApi:
          path: /users-rds
          method: post
      - cloudwatchLog: '/aws/lambda/go-lambda-create-user-rds'
  go-lambda-get-all-users:
    handler: lambdas/bin/go-lambda-get-all-users
    events:
      - httpApi:
          path: /users
          method: get
      - cloudwatchLog: '/aws/lambda/go-lambda-get-all-users'


#    Define function environment variables here
#    environment:
#      variable2: value2

resources:
  Resources:

    ReceiptsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.stage}-${self:service}-receipts

    WorldLambdaLogs:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: /aws/lambda/world
    goLambdaCreateUserLogs:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: /aws/lambda/go-lambda-create-user
    goLambdaCreateUserRdsLogs:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: /aws/lambda/go-lambda-create-user-rds
    goLambdaGetAllUsersLogs:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: /aws/lambda/go-lambda-get-all-users

    auroraCluster:
      Type: AWS::RDS::DBCluster
      Properties:
        DatabaseName: prodOlgaBackend
        Engine: aurora-postgresql
        EngineVersion: "14.6"
        MasterUsername: ${ssm:/db_username}
        MasterUserPassword: ${ssm:/db_password}
        ServerlessV2ScalingConfiguration:
          MinCapacity: 0.5
          MaxCapacity: 4
    auroraInstance:
      Type: "AWS::RDS::DBInstance"
      Properties:
        PubliclyAccessible: true
        Engine: aurora-postgresql
        DBInstanceClass: db.serverless
        DBClusterIdentifier: !Ref auroraCluster
    auroraReadReplica:
      Type: "AWS::RDS::DBInstance"
      Properties:
        PubliclyAccessible: true
        Engine: aurora-postgresql
        DBInstanceClass: db.serverless
        DBClusterIdentifier: !Ref auroraCluster

    users:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: email-index
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL

plugins:
  - serverless-domain-manager
  - serverless-ssm-fetch

custom:
  serverlessSsmFetch:
    EMAIL_SENDER_ADDRESS: /email_sender_address
    EMAIL_SENDER_PASSWORD: /email_sender_password
    DB_USER: /db_username
    DB_PASSWORD: /db_password
    DB_NAME: /db_name
    DB_HOST_WRITER: /db_host_writer_instance
    DB_HOST_READER: /db_host_reader_instance
  customDomain:
    domainName: 'api.olga.lat'
    basePath: 'api'
    stage: ${self:provider.stage}
    createRoute53Record: true
    endpointType: regional
    apiType: http

